services:
  mysql-db-inventory:
    image: mariadb:10.6
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: root
      MYSQL_PASSWORD:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  mysql_data: